name: oursms
description: A spy for SMS messages.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sms_maintained: ^0.2.5
  timelines: ^0.1.0
  enum_to_string: ^2.0.1
  crypto: ^3.0.1
  provider: ^6.0.0
  flutter_multi_formatter: ^2.3.5
  cupertino_icons: ^1.0.2
  firebase_database: ^8.0.0
  firebase_core: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
